clone:
  path: github.com/udistrital/cancelacion_semestre_api

test:
  image: golang:1.8
  commands:
    - echo testing
    - cd tests && go test

build:
  image: golang:1.8s
  commands:
    - echo building
    - mkdir -p target
    - GOOS=linux GOARCH=amd64 go build -o target/update-tuleap-$${COMMIT:0:7}-linux-x86_64
    - GOOS=windows GOARCH=amd64 go build -o target/update-tuleap-$${COMMIT:0:7}-windows-x86_64.exe
    - GOOS=darwin GOARCH=amd64 go build -o target/update-tuleap-$${COMMIT:0:7}-darwin-x86_64

package:
  image: alpine
  commands:
    - echo packaging
    - echo tar cf package-$$BRANCH-$${COMMIT:0:7}-$$BUILD_NUMBER.tar index.html bundle.js
    - echo gzip package-$$BRANCH-$${COMMIT:0:7}-$$BUILD_NUMBER.tar
    - echo jorge hacer algo con el binario que se compilo antes, ver el proyecto update_tuleap para un ejemplo
