test:
  image: golang
  commands:
    - echo testing
    - cd tests && go test

build:
  image: golang
  commands:
    - echo building
    - go build

package:
  image: alpine
  commands:
    - echo packaging
    - echo tar cf package-$$BRANCH-$${COMMIT:0:7}-$$BUILD_NUMBER.tar index.html bundle.js
    - echo gzip package-$$BRANCH-$${COMMIT:0:7}-$$BUILD_NUMBER.tar
    - echo jorge hacer algo con el binario que se compilo antes, ver el proyecto coasverage_api para un ejemplo
