language: go
go:
- 1.7.x
script:
- go test -v ./...
- GOOS=linux GOARCH=amd64 go build -o cancelacion_semestre_api main.go
deploy:
  provider: releases
  api_key:
    secure: deBn3DNlrs/Dt6GQFeF7tRjkKWU/Ky9U1nf6T2etl9QVbfcjMZncflTGzneJYMJd/QI5i7il/Wgd3jCTAwV6pTH5e9Auwsk8OGGsOWWQrqzB9rEgzmoCu1rT6VLkOVj5dUveOKACRVpVjRSpSf9P6C9SmTwPajd1DdhgaHUi87ua5qSfHZEyu2j7iK2ZNz/4WQkL+nEoixb7cMCOLet6noGIWzcR03BD5b2EwEgt5CjWu3qXUmkhmn+ra3xqJSJ8zeqem+f6yNpSTO2aHN+R5DnK8ZcqWR2yu0b/as/Fh3a0Qe9LTrAzVICeo89svr/9c0wHee/X28SUbiGExuJYkyB7TQ+Qat2Ct/IVHdWynV9hpUpo/+2+40wJ1rrAEEHqzTS2G1GDl0vadlfseWLbijn+IwuhICL8Q4896PM319+2X6uc6FmQIwox8Y6gtoDgZWhHYe7lgUkoM8he1el1ibB641meYD7W9MX+6qvUehZJxQGS00SEHHjZhZya4zeXwmNxQaTLBdp5ZsG9Jk4jz+Vrhs85ZJ+YsElAVGSwAL0US0SKD+X+GfT5PPdb9QHXtti4bLWiKfy5/RYHNrcf+6aJtI6QA5rgev24YKer3XY9Jttm4RcPPHZ6cghyeKji8IHhIvb+fr7xqYiZYtAYsz2merScB4aPPE2cxwroJpA=
  file: cancelacion_semestre_api
  skip_cleanup: true
  on:
    repo: udistrital/cancelacion_semestre_api
    tags: true
